# Generated by Django 6.0.2 on 2026-03-06 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('source', models.CharField(blank=True, help_text='Which product brought them in', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('mrr_cents', models.IntegerField(default=0, help_text='Monthly Recurring Revenue')),
                ('total_revenue_cents', models.IntegerField(default=0, help_text='Total revenue that day')),
                ('new_customers', models.IntegerField(default=0)),
                ('churned', models.IntegerField(default=0)),
                ('active_subscriptions', models.IntegerField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Revenue per product')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_id', models.CharField(max_length=100, unique=True)),
                ('product', models.CharField(max_length=100)),
                ('amount_cents', models.IntegerField()),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('status', models.CharField(default='succeeded', max_length=30)),
                ('payment_type', models.CharField(default='subscription', help_text='subscription, one_time, invoice', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('receipt_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_created', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=100, unique=True)),
                ('product', models.CharField(choices=[('onyx_pro', 'Onyx POS Pro -- $49/mo'), ('hivemind_starter', 'Hive Mind Starter -- $29/mo'), ('hivemind_pro', 'Hive Mind Pro -- $79/mo'), ('hivemind_enterprise', 'Hive Mind Enterprise -- $149/mo'), ('alley_kingz_vip', 'Alley Kingz VIP -- $4.99/mo')], max_length=50)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('paused', 'Paused')], default='trialing', max_length=20)),
                ('amount_cents', models.IntegerField(help_text='Monthly amount in cents')),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payments.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
