# Generated by Django 6.0.2 on 2026-03-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='product',
            field=models.CharField(choices=[('onyx_pro', 'Onyx POS Pro -- $49/mo'), ('hivemind_starter', 'Hive Mind Starter -- $29/mo'), ('hivemind_pro', 'Hive Mind Pro -- $79/mo'), ('hivemind_enterprise', 'Hive Mind Enterprise -- $149/mo'), ('alley_kingz_vip', 'Alley Kingz VIP -- $4.99/mo'), ('ai_consulting_retainer', 'AI Consulting Retainer -- $2,000/mo')], max_length=50),
        ),
        migrations.CreateModel(
            name='ConsultingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('vertical', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('discovery', 'Discovery Call'), ('proposal', 'Proposal Sent'), ('building', 'Building'), ('delivered', 'Delivered'), ('retainer', 'Active Retainer'), ('churned', 'Churned')], default='discovery', max_length=20)),
                ('discovery_date', models.DateTimeField(blank=True, null=True)),
                ('build_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retainer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('solutions_deployed', models.JSONField(blank=True, default=list, help_text='["lead_gen_bot", "support_bot"]')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulting_projects', to='payments.customer')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
