"""
PDF Report Generator - Branded Everlight Ventures reports.
Uses reportlab for professional PDF generation.
"""
import os
from datetime import datetime
from pathlib import Path

OUTPUT_DIR = Path(os.environ.get("DELIVERABLES_DIR", "/tmp/hive_deliverables"))
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Brand colors
GOLD = (0.83, 0.63, 0.09)      # #D4A017
DARK = (0.1, 0.1, 0.1)         # #1A1A1A
GRAY = (0.4, 0.4, 0.4)
WHITE = (1, 1, 1)


def generate_pdf(title: str, sections: list[dict], subtitle: str = "",
                 author: str = "Everlight Ventures") -> str:
    """
    Generate a branded PDF report.

    Args:
        title: Report title
        sections: List of {"heading": str, "body": str, "table": list[dict] (optional)}
        subtitle: Optional subtitle/date line
        author: Author name

    Returns:
        Path to generated PDF file
    """
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        )
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import Color
    except ImportError:
        # Fallback: generate a simple text file if reportlab not installed
        return _fallback_text(title, sections, subtitle)

    filename = f"{title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"
    filepath = OUTPUT_DIR / filename

    doc = SimpleDocTemplate(
        str(filepath), pagesize=letter,
        topMargin=0.75 * inch, bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    gold_color = Color(*GOLD)
    dark_color = Color(*DARK)

    # Custom styles
    title_style = ParagraphStyle(
        "EVTitle", parent=styles["Title"],
        fontSize=24, textColor=dark_color, spaceAfter=6,
        fontName="Helvetica-Bold",
    )
    subtitle_style = ParagraphStyle(
        "EVSubtitle", parent=styles["Normal"],
        fontSize=11, textColor=Color(*GRAY), spaceAfter=20,
    )
    heading_style = ParagraphStyle(
        "EVHeading", parent=styles["Heading2"],
        fontSize=14, textColor=gold_color, spaceBefore=16, spaceAfter=8,
        fontName="Helvetica-Bold",
    )
    body_style = ParagraphStyle(
        "EVBody", parent=styles["Normal"],
        fontSize=10, textColor=dark_color, spaceAfter=8,
        leading=14,
    )
    footer_style = ParagraphStyle(
        "EVFooter", parent=styles["Normal"],
        fontSize=8, textColor=Color(*GRAY), alignment=1,
    )

    # Build content
    story = []

    # Gold accent bar
    story.append(HRFlowable(width="100%", thickness=3, color=gold_color, spaceAfter=12))

    # Title
    story.append(Paragraph(title, title_style))
    sub = subtitle or f"{author} | {datetime.now().strftime('%B %d, %Y')}"
    story.append(Paragraph(sub, subtitle_style))

    # Sections
    for section in sections:
        if section.get("heading"):
            story.append(Paragraph(section["heading"], heading_style))

        if section.get("body"):
            for line in section["body"].split("\n"):
                if line.strip():
                    story.append(Paragraph(line, body_style))

        if section.get("table"):
            rows = section["table"]
            if rows:
                headers = list(rows[0].keys())
                data = [headers] + [[str(r.get(h, "")) for h in headers] for r in rows]
                t = Table(data, repeatRows=1)
                t.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), gold_color),
                    ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("GRID", (0, 0), (-1, -1), 0.5, Color(*GRAY)),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, Color(0.97, 0.97, 0.97)]),
                    ("PADDING", (0, 0), (-1, -1), 6),
                ]))
                story.append(Spacer(1, 8))
                story.append(t)

        story.append(Spacer(1, 8))

    # Footer
    story.append(Spacer(1, 24))
    story.append(HRFlowable(width="100%", thickness=1, color=Color(*GRAY), spaceAfter=8))
    story.append(Paragraph(
        f"Generated by Everlight Ventures Hive Mind | {datetime.now().strftime('%Y-%m-%d %H:%M PT')} | everlightventures.io",
        footer_style,
    ))

    doc.build(story)
    return str(filepath)


def _fallback_text(title, sections, subtitle):
    """Fallback when reportlab is not installed."""
    filename = f"{title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M')}.txt"
    filepath = OUTPUT_DIR / filename
    lines = [f"{'=' * 60}", title, subtitle or datetime.now().strftime('%B %d, %Y'), f"{'=' * 60}", ""]
    for s in sections:
        if s.get("heading"):
            lines.append(f"\n## {s['heading']}")
        if s.get("body"):
            lines.append(s["body"])
        if s.get("table"):
            for row in s["table"]:
                lines.append(" | ".join(f"{k}: {v}" for k, v in row.items()))
    lines.append(f"\n---\nGenerated by Everlight Ventures Hive Mind")
    filepath.write_text("\n".join(lines))
    return str(filepath)
