"""
Broker OS -- Contract Generator
Auto-generates professional PDF finder fee agreements from deal data.
Populates templates with buyer/seller info, commission rates, scope.

Usage:
    from contract_generator import generate_finder_agreement, generate_wholesale_contract
    path = generate_finder_agreement(deal_data)
    path = generate_wholesale_contract(deal_data)
"""
from __future__ import annotations
import os
import json
from datetime import datetime, timezone, timedelta
from pathlib import Path

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY

# Directories
CONTRACTS_DIR = Path(os.getenv(
    "CONTRACTS_DIR",
    "/mnt/sdcard/AA_MY_DRIVE/01_BUSINESSES/Everlight_Ventures/Broker_OS/wholesale_agent/contracts"
))
CONTRACTS_DIR.mkdir(parents=True, exist_ok=True)

# Brand colors
GOLD = HexColor("#D4A017")
DARK = HexColor("#1a1a2e")
GRAY = HexColor("#555555")

# Company info
COMPANY = {
    "name": "Everlight Logistics LLC",
    "dba": "Everlight Ventures",
    "address": "",
    "email": "deals@everlightventures.io",
    "state": "California",
}


def _build_styles():
    """Create branded paragraph styles."""
    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle(
            "ContractTitle", parent=base["Title"],
            fontSize=22, textColor=DARK, spaceAfter=6,
            fontName="Helvetica-Bold",
        ),
        "subtitle": ParagraphStyle(
            "ContractSubtitle", parent=base["Normal"],
            fontSize=11, textColor=GOLD, spaceAfter=12,
            fontName="Helvetica-Bold", alignment=TA_CENTER,
        ),
        "heading": ParagraphStyle(
            "SectionHeading", parent=base["Heading2"],
            fontSize=12, textColor=DARK, spaceBefore=16, spaceAfter=6,
            fontName="Helvetica-Bold",
        ),
        "body": ParagraphStyle(
            "ContractBody", parent=base["Normal"],
            fontSize=10, leading=14, textColor=GRAY,
            fontName="Helvetica", alignment=TA_JUSTIFY,
        ),
        "bold": ParagraphStyle(
            "ContractBold", parent=base["Normal"],
            fontSize=10, leading=14, textColor=DARK,
            fontName="Helvetica-Bold",
        ),
        "small": ParagraphStyle(
            "ContractSmall", parent=base["Normal"],
            fontSize=8, textColor=HexColor("#888888"),
            fontName="Helvetica",
        ),
        "signature": ParagraphStyle(
            "Signature", parent=base["Normal"],
            fontSize=10, textColor=DARK, spaceBefore=30,
            fontName="Helvetica",
        ),
    }
    return styles


def _header_footer(canvas, doc, title="FINDER FEE AGREEMENT"):
    """Draw branded header and footer on each page."""
    canvas.saveState()
    # Header line
    canvas.setStrokeColor(GOLD)
    canvas.setLineWidth(2)
    canvas.line(72, 750, 540, 750)
    # Footer
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(HexColor("#aaaaaa"))
    canvas.drawString(72, 30, "Generated by Everlight Ventures Broker OS | %s" % datetime.now().strftime("%B %d, %Y"))
    canvas.drawRightString(540, 30, "Page %d" % doc.page)
    # Gold accent bar at bottom
    canvas.setStrokeColor(GOLD)
    canvas.setLineWidth(1)
    canvas.line(72, 40, 540, 40)
    canvas.restoreState()


def _pt_now():
    return datetime.now(timezone(timedelta(hours=-7)))


def generate_finder_agreement(deal: dict) -> str:
    """
    Generate a Finder Fee Agreement PDF.

    deal dict should contain:
        client_name: str        - buyer/client company name
        client_contact: str     - contact person name
        client_email: str       - contact email
        scope: str              - what is being brokered
        commission_pct: float   - e.g. 0.20 for 20%
        deal_value: float       - estimated deal value (optional)
        term_months: int        - agreement term (default 12)
        state: str              - governing law state (default California)

    Returns: path to generated PDF
    """
    client = deal.get("client_name", "Unknown Client")
    contact = deal.get("client_contact", "")
    email = deal.get("client_email", "")
    scope = deal.get("scope", "SaaS product/service introduction")
    pct = deal.get("commission_pct", 0.20)
    value = deal.get("deal_value", 0)
    term = deal.get("term_months", 12)
    state = deal.get("state", COMPANY["state"])
    date_str = _pt_now().strftime("%B %d, %Y")

    safe_name = "".join(c if c.isalnum() or c in "._- " else "_" for c in client)
    filename = "finder_agreement_%s_%s.pdf" % (safe_name, _pt_now().strftime("%Y%m%d"))
    filepath = CONTRACTS_DIR / filename

    doc = SimpleDocTemplate(
        str(filepath), pagesize=letter,
        leftMargin=72, rightMargin=72, topMargin=80, bottomMargin=60,
    )
    styles = _build_styles()
    story = []

    # Title
    story.append(Paragraph("FINDER FEE AGREEMENT", styles["title"]))
    story.append(Paragraph("Everlight Ventures Broker OS", styles["subtitle"]))
    story.append(HRFlowable(width="100%", thickness=1, color=GOLD, spaceAfter=12))

    # Date + parties
    story.append(Paragraph("<b>Date:</b> %s" % date_str, styles["body"]))
    story.append(Spacer(1, 8))

    parties_data = [
        ["FINDER", "CLIENT"],
        [
            "%s\nd/b/a %s\n%s" % (COMPANY["name"], COMPANY["dba"], COMPANY["email"]),
            "%s\n%s\n%s" % (client, contact, email),
        ],
    ]
    parties_table = Table(parties_data, colWidths=[230, 230])
    parties_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), GOLD),
        ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#FFFFFF")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#cccccc")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(parties_table)
    story.append(Spacer(1, 16))

    # Section 1: Scope
    story.append(Paragraph("1. SCOPE OF ENGAGEMENT", styles["heading"]))
    story.append(Paragraph(
        "Finder agrees to introduce Client to qualified buyers, partners, or customers "
        "for the following product/service:",
        styles["body"],
    ))
    story.append(Spacer(1, 6))
    story.append(Paragraph('<i>"%s"</i>' % scope, styles["bold"]))
    story.append(Spacer(1, 8))

    # Section 2: Compensation
    story.append(Paragraph("2. COMPENSATION", styles["heading"]))
    pct_display = "%.0f%%" % (pct * 100)
    value_str = " (estimated value: $%s)" % "{:,.0f}".format(value) if value else ""
    story.append(Paragraph(
        "Client agrees to pay Finder a fee of <b>%s</b> of the gross transaction "
        "value%s for any deal closed with an introduction made by Finder." % (pct_display, value_str),
        styles["body"],
    ))
    story.append(Spacer(1, 6))
    bullet_items = [
        "Payment due: Net 30 from close date via Stripe invoice or bank transfer",
        "Commission applies to initial transaction and any renewals or expansions within 12 months of the original introduction",
        "Minimum finder fee: $500 per closed transaction",
    ]
    for item in bullet_items:
        story.append(Paragraph("&bull; %s" % item, styles["body"]))

    # Section 3: Term
    story.append(Paragraph("3. TERM", styles["heading"]))
    story.append(Paragraph(
        "This agreement is effective for <b>%d months</b> from the date above. "
        "Introductions made during this period remain compensable even if the deal "
        "closes after expiration." % term,
        styles["body"],
    ))

    # Section 4: Finder's Role (Legal safe harbor)
    story.append(Paragraph("4. FINDER'S ROLE - LIMITATIONS", styles["heading"]))
    story.append(Paragraph(
        "Finder's role is LIMITED to introductions only. Finder does NOT:",
        styles["body"],
    ))
    limitations = [
        "Negotiate terms on behalf of either party",
        "Handle client funds, securities, or escrow",
        "Provide investment, legal, or financial advice",
        "Act as a broker-dealer or licensed agent",
        "Guarantee any specific outcome or transaction",
    ]
    for item in limitations:
        story.append(Paragraph("&bull; %s" % item, styles["body"]))

    # Section 5: Quality Assurance Review
    story.append(Paragraph("5. QUALITY ASSURANCE REVIEW PERIOD", styles["heading"]))
    story.append(Paragraph(
        "Client shall have a <b>48-hour review period</b> after any introduction to evaluate "
        "the quality and relevance of the match. If Client determines the introduction does not "
        "meet their stated criteria, Client may decline without obligation. Once Client engages "
        "in substantive communication with the introduced party beyond the review period, "
        "the introduction is deemed accepted.",
        styles["body"],
    ))

    # Section 6: Non-Circumvention
    story.append(Paragraph("6. NON-CIRCUMVENTION", styles["heading"]))
    story.append(Paragraph(
        "Client agrees not to circumvent Finder by dealing directly with introduced "
        "parties without Finder's knowledge and commission payment. This protection "
        "extends for 24 months from the date of introduction.",
        styles["body"],
    ))

    # Section 7: Confidentiality
    story.append(Paragraph("7. CONFIDENTIALITY", styles["heading"]))
    story.append(Paragraph(
        "Both parties agree to keep the terms of this agreement and any proprietary "
        "information exchanged during the engagement confidential.",
        styles["body"],
    ))

    # Section 8: Governing Law
    story.append(Paragraph("8. GOVERNING LAW", styles["heading"]))
    story.append(Paragraph(
        "This agreement is governed by the laws of the State of <b>%s</b>. "
        "Any disputes shall be resolved through binding arbitration in %s." % (state, state),
        styles["body"],
    ))

    # Signatures
    story.append(Spacer(1, 30))
    story.append(HRFlowable(width="100%", thickness=1, color=GOLD, spaceAfter=12))

    sig_data = [
        ["FINDER", "", "CLIENT", ""],
        [COMPANY["name"], "", client, ""],
        ["Signature: ____________________", "Date: ________", "Signature: ____________________", "Date: ________"],
        ["Print Name: __________________", "", "Print Name: __________________", ""],
        ["Title: _______________________", "", "Title: _______________________", ""],
    ]
    sig_table = Table(sig_data, colWidths=[175, 60, 175, 60])
    sig_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (-1, 0), GOLD),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(sig_table)

    # Disclaimer
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "<i>This agreement is generated by Everlight Ventures Broker OS. "
        "Both parties should consult legal counsel before execution, especially "
        "for deals involving securities, real estate, or regulated industries. "
        "This document does not constitute legal advice.</i>",
        styles["small"],
    ))

    # Build PDF
    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)

    # Save metadata alongside PDF
    meta = {
        "type": "finder_agreement",
        "client": client,
        "contact": contact,
        "email": email,
        "scope": scope,
        "commission_pct": pct,
        "deal_value": value,
        "term_months": term,
        "state": state,
        "generated_at": _pt_now().isoformat(),
        "pdf_path": str(filepath),
    }
    meta_path = filepath.with_suffix(".json")
    meta_path.write_text(json.dumps(meta, indent=2))

    return str(filepath)


def generate_wholesale_contract(deal: dict) -> str:
    """
    Generate a Wholesale Real Estate Purchase Agreement PDF.

    deal dict should contain:
        property_address: str
        seller_name: str
        seller_email: str
        buyer_name: str
        buyer_email: str
        purchase_price: float
        assignment_fee: float
        earnest_money: float
        closing_date: str (YYYY-MM-DD)
        title_company: str
        inspection_days: int (default 14)
    """
    prop = deal.get("property_address", "TBD")
    seller = deal.get("seller_name", "Unknown Seller")
    seller_email = deal.get("seller_email", "")
    buyer = deal.get("buyer_name", "Unknown Buyer")
    buyer_email = deal.get("buyer_email", "")
    price = deal.get("purchase_price", 0)
    fee = deal.get("assignment_fee", 0)
    earnest = deal.get("earnest_money", 500)
    closing = deal.get("closing_date", "TBD")
    title_co = deal.get("title_company", "TBD")
    inspect_days = deal.get("inspection_days", 14)
    date_str = _pt_now().strftime("%B %d, %Y")

    safe_addr = "".join(c if c.isalnum() or c in "._- " else "_" for c in prop[:40])
    filename = "wholesale_%s_%s.pdf" % (safe_addr, _pt_now().strftime("%Y%m%d"))
    filepath = CONTRACTS_DIR / filename

    doc = SimpleDocTemplate(
        str(filepath), pagesize=letter,
        leftMargin=72, rightMargin=72, topMargin=80, bottomMargin=60,
    )
    styles = _build_styles()
    story = []

    # Title
    story.append(Paragraph("REAL ESTATE PURCHASE AGREEMENT", styles["title"]))
    story.append(Paragraph("Assignable Wholesale Contract", styles["subtitle"]))
    story.append(HRFlowable(width="100%", thickness=1, color=GOLD, spaceAfter=12))
    story.append(Paragraph("<b>Date:</b> %s" % date_str, styles["body"]))
    story.append(Spacer(1, 8))

    # Property + parties table
    info_data = [
        ["PROPERTY", prop],
        ["SELLER", "%s (%s)" % (seller, seller_email)],
        ["BUYER / ASSIGNEE", "%s (%s)" % (buyer, buyer_email)],
        ["PURCHASE PRICE", "$%s" % "{:,.0f}".format(price)],
        ["ASSIGNMENT FEE", "$%s" % "{:,.0f}".format(fee)],
        ["EARNEST MONEY", "$%s" % "{:,.0f}".format(earnest)],
        ["CLOSING DATE", closing],
        ["TITLE COMPANY", title_co],
        ["INSPECTION PERIOD", "%d calendar days" % inspect_days],
    ]
    info_table = Table(info_data, colWidths=[140, 330])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), HexColor("#f5f0e8")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#cccccc")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 16))

    # Terms
    sections = [
        ("1. AGREEMENT TO PURCHASE", (
            "Seller agrees to sell and Buyer agrees to purchase the property located at "
            "<b>%s</b> for the sum of <b>$%s</b>." % (prop, "{:,.0f}".format(price))
        )),
        ("2. EARNEST MONEY DEPOSIT", (
            "Buyer shall deposit <b>$%s</b> as earnest money with %s "
            "within 3 business days of mutual execution of this agreement." % ("{:,.0f}".format(earnest), title_co)
        )),
        ("3. INSPECTION PERIOD", (
            "Buyer shall have <b>%d calendar days</b> from mutual execution "
            "to conduct inspections. Buyer may terminate this agreement for any reason during "
            "the inspection period and receive a full refund of earnest money." % inspect_days
        )),
        ("4. ASSIGNMENT", (
            "This contract IS ASSIGNABLE. Buyer may assign this contract to a third party "
            "for an assignment fee of <b>$%s</b>. Seller acknowledges and consents "
            "to assignment. Buyer is Richard Gee doing business as Everlight Ventures, "
            "a California sole proprietor. (See BUSINESS_ENTITY_STATUS.md for current "
            "entity status. Update this clause once the Everlight Ventures LLC is reinstated.)" % "{:,.0f}".format(fee)
        )),
        ("5. CLOSING", (
            "Closing shall occur on or before <b>%s</b> at %s. "
            "Seller shall provide clear and marketable title. Standard closing costs "
            "apply per local custom." % (closing, title_co)
        )),
        ("6. AS-IS CONDITION", (
            "Property is sold in AS-IS condition. Seller makes no warranties regarding "
            "the condition of the property. Buyer has had opportunity to inspect."
        )),
        ("7. DEFAULT", (
            "If Buyer defaults, Seller's sole remedy is retention of earnest money as "
            "liquidated damages. If Seller defaults, Buyer may seek specific performance "
            "or return of earnest money."
        )),
        ("8. QUALITY ASSURANCE REVIEW PERIOD", (
            "Seller shall have a <b>7-calendar-day Quality Assurance Review Period</b> "
            "beginning on mutual execution of this agreement. During this period Seller may "
            "rescind this agreement for any reason by written notice (email accepted) and "
            "receive return of all deposits without penalty or obligation. This right is in "
            "addition to any state-mandated rescission periods. Everlight Ventures commits to "
            "the CarMax standard: a fair deal or no deal."
        )),
        ("9. GOVERNING LAW", (
            "This agreement is governed by the laws of the state where the property is located."
        )),
    ]

    for heading, text in sections:
        story.append(Paragraph(heading, styles["heading"]))
        story.append(Paragraph(text, styles["body"]))

    # Signatures
    story.append(Spacer(1, 30))
    story.append(HRFlowable(width="100%", thickness=1, color=GOLD, spaceAfter=12))

    sig_data = [
        ["SELLER", "", "BUYER / ASSIGNEE", ""],
        [seller, "", buyer, ""],
        ["Signature: ____________________", "Date: ________", "Signature: ____________________", "Date: ________"],
        ["Print Name: __________________", "", "Print Name: __________________", ""],
    ]
    sig_table = Table(sig_data, colWidths=[175, 60, 175, 60])
    sig_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (-1, 0), GOLD),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(sig_table)

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "<i>This is a template contract generated by Everlight Ventures Broker OS. "
        "Consult a licensed real estate attorney in the property's state before execution. "
        "This document does not constitute legal advice.</i>",
        styles["small"],
    ))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)

    # Metadata
    meta = {
        "type": "wholesale_purchase_agreement",
        "property": prop,
        "seller": seller,
        "buyer": buyer,
        "purchase_price": price,
        "assignment_fee": fee,
        "generated_at": _pt_now().isoformat(),
        "pdf_path": str(filepath),
    }
    filepath.with_suffix(".json").write_text(json.dumps(meta, indent=2))

    return str(filepath)


if __name__ == "__main__":
    # Test: generate sample contracts
    print("Generating sample finder agreement...")
    p1 = generate_finder_agreement({
        "client_name": "TechCorp Inc",
        "client_contact": "Jane Smith",
        "client_email": "jane@techcorp.com",
        "scope": "AI-powered customer support chatbot implementation",
        "commission_pct": 0.20,
        "deal_value": 25000,
        "term_months": 12,
    })
    print("  -> %s" % p1)

    print("Generating sample wholesale contract...")
    p2 = generate_wholesale_contract({
        "property_address": "1234 Oak St, Cleveland OH 44102",
        "seller_name": "John Doe",
        "seller_email": "john@email.com",
        "buyer_name": "REI Capital LLC",
        "buyer_email": "deals@reicapital.com",
        "purchase_price": 85000,
        "assignment_fee": 12000,
        "earnest_money": 1000,
        "closing_date": "May 15, 2026",
        "title_company": "First American Title",
        "inspection_days": 14,
    })
    print("  -> %s" % p2)
    print("Done.")
