"""
Monthly GMV Billing Job
Runs on the 1st of each month at 00:00 UTC

Responsibilities:
1. Calculate GMV for all active tenants for previous month
2. Submit usage records to Stripe for metered billing
3. Roll GMV counters (current → last, reset current)
4. Log billing events for audit
"""
from datetime import datetime, timedelta
from database import Session
from models import Tenant
from services.stripe_metered import record_gmv_usage
import sys


def run_monthly_billing(dry_run=False):
    """
    Execute monthly billing for all tenants

    Args:
        dry_run: If True, calculate but don't submit to Stripe

    Returns:
        dict: Summary of billing run
    """
    print("\n" + "=" * 60)
    print("  OnyxPOS Monthly GMV Billing")
    print(f"  Run Date: {datetime.utcnow().isoformat()}")
    print(f"  Mode: {'DRY RUN' if dry_run else 'LIVE'}")
    print("=" * 60 + "\n")

    db = Session()
    summary = {
        'total_tenants': 0,
        'billed_tenants': 0,
        'skipped_tenants': 0,
        'errors': 0,
        'total_gmv': 0.0,
        'total_fees': 0.0,
        'results': []
    }

    try:
        # Get billing period (previous month)
        now = datetime.utcnow()
        first_of_month = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
        billing_period = (first_of_month - timedelta(days=1)).strftime('%Y-%m')  # Previous month

        print(f"📅 Billing Period: {billing_period}\n")

        # Get all active tenants (active or past_due)
        tenants = db.query(Tenant).filter(
            Tenant.subscription_status.in_(['active', 'past_due', 'trial'])
        ).all()

        summary['total_tenants'] = len(tenants)
        print(f"Found {len(tenants)} active tenants\n")

        for tenant in tenants:
            result = process_tenant_billing(tenant, billing_period, dry_run, db)
            summary['results'].append(result)

            if result['status'] == 'billed':
                summary['billed_tenants'] += 1
                summary['total_gmv'] += result['gmv']
                summary['total_fees'] += result['usage_fee']
            elif result['status'] == 'skipped':
                summary['skipped_tenants'] += 1
            elif result['status'] == 'error':
                summary['errors'] += 1

        # Print summary
        print("\n" + "=" * 60)
        print("  Billing Run Summary")
        print("=" * 60)
        print(f"  Total Tenants:     {summary['total_tenants']}")
        print(f"  Billed:            {summary['billed_tenants']}")
        print(f"  Skipped:           {summary['skipped_tenants']}")
        print(f"  Errors:            {summary['errors']}")
        print(f"  Total GMV:         ${summary['total_gmv']:,.2f}")
        print(f"  Total Fees:        ${summary['total_fees']:,.2f}")
        print("=" * 60 + "\n")

        if dry_run:
            print("⚠️  DRY RUN - No charges were submitted to Stripe\n")
        else:
            print("✅ Billing run complete - Invoices will be generated by Stripe\n")

        return summary

    except Exception as e:
        print(f"❌ Fatal error during billing run: {e}")
        summary['fatal_error'] = str(e)
        return summary

    finally:
        db.close()


def process_tenant_billing(tenant, billing_period, dry_run, db):
    """
    Process billing for a single tenant

    Args:
        tenant: Tenant model instance
        billing_period: String like "2025-01"
        dry_run: Boolean
        db: Database session

    Returns:
        dict: Result of billing operation
    """
    result = {
        'tenant_id': tenant.id,
        'business_name': tenant.business_name,
        'plan_tier': tenant.plan_tier,
        'status': 'pending',
        'gmv': 0.0,
        'usage_fee': 0.0,
        'cap_reached': False,
        'error': None
    }

    try:
        # Get GMV for current month (which is actually last month now)
        gmv = float(tenant.gmv_current_month or 0)
        result['gmv'] = gmv

        # Skip if no GMV
        if gmv == 0:
            print(f"⏭️  {tenant.business_name}: No GMV, skipping")
            result['status'] = 'skipped'
            result['skip_reason'] = 'no_gmv'
            return result

        # Skip if no Stripe subscription (trial without payment)
        if not tenant.stripe_subscription_id:
            print(f"⏭️  {tenant.business_name}: No subscription, skipping")
            result['status'] = 'skipped'
            result['skip_reason'] = 'no_subscription'
            return result

        # Calculate usage fee
        usage_fee = tenant.calculate_usage_fee(gmv)
        result['usage_fee'] = usage_fee

        # Check if cap was reached
        cap = tenant.get_variable_fee_cap()
        uncapped_fee = gmv * (tenant.get_platform_fee_percent() / 100)
        result['cap_reached'] = cap > 0 and uncapped_fee > cap
        result['savings'] = round(uncapped_fee - usage_fee, 2) if result['cap_reached'] else 0

        print(f"💰 {tenant.business_name}:")
        print(f"   GMV: ${gmv:,.2f}")
        print(f"   Usage Fee: ${usage_fee:.2f} ({tenant.get_platform_fee_percent()}%)")
        if result['cap_reached']:
            print(f"   🎯 Cap Reached! Saved ${result['savings']:.2f}")

        # Submit to Stripe (unless dry run)
        if not dry_run:
            stripe_result = record_gmv_usage(tenant, gmv, billing_period)

            if stripe_result['success']:
                print(f"   ✅ Submitted to Stripe (Record ID: {stripe_result.get('usage_record_id', 'N/A')})")

                # Roll GMV counters
                tenant.gmv_last_month = tenant.gmv_current_month
                tenant.gmv_current_month = 0
                tenant.usage_fee_current_month = usage_fee
                tenant.last_gmv_reset = datetime.utcnow()
                db.commit()

                result['status'] = 'billed'
                result['usage_record_id'] = stripe_result.get('usage_record_id')
            else:
                print(f"   ❌ Stripe error: {stripe_result.get('error')}")
                result['status'] = 'error'
                result['error'] = stripe_result.get('error')
        else:
            print(f"   🔍 DRY RUN - Would submit ${usage_fee:.2f} to Stripe")
            result['status'] = 'billed'  # Mark as billed for summary

        print()
        return result

    except Exception as e:
        print(f"❌ {tenant.business_name}: Error - {e}\n")
        result['status'] = 'error'
        result['error'] = str(e)
        return result


if __name__ == '__main__':
    """
    Run from command line:
        python -m jobs.monthly_billing
        python -m jobs.monthly_billing --dry-run
    """
    dry_run = '--dry-run' in sys.argv or '-d' in sys.argv

    summary = run_monthly_billing(dry_run=dry_run)

    # Exit with error code if there were errors
    if summary.get('errors', 0) > 0 or summary.get('fatal_error'):
        sys.exit(1)
    else:
        sys.exit(0)
