# Generated by Django 6.0.2 on 2026-03-12 20:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(default=0.0, help_text='0-100, AI-generated')),
                ('match_reasoning', models.TextField(blank=True, help_text='Why this pair was matched')),
                ('matched_by', models.CharField(default='auto', help_text='auto, manual, claude', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Outreach Sent'), ('declined', 'Declined'), ('converted', 'Converted to Deal'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('outreach_sent_at', models.DateTimeField(blank=True, null=True)),
                ('outreach_channel', models.CharField(blank=True, help_text='email, slack, dm', max_length=50)),
                ('outreach_template', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Broker Match',
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, help_text='CTO, Founder, etc.', max_length=100)),
                ('company_size', models.CharField(blank=True, choices=[('1_10', '1-10'), ('11_50', '11-50'), ('51_200', '51-200'), ('200_plus', '200+')], max_length=20)),
                ('need_description', models.TextField(help_text="What they're looking for")),
                ('categories_needed', models.JSONField(default=list, help_text='List of category keys they need')),
                ('budget_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('intent', models.CharField(choices=[('hot', 'Hot - ready to buy'), ('warm', 'Warm - evaluating'), ('cold', 'Cold - researching')], default='warm', max_length=10)),
                ('lead_source', models.CharField(choices=[('inbound_email', 'Inbound Email'), ('product_hunt', 'Product Hunt'), ('linkedin', 'LinkedIn'), ('twitter_x', 'Twitter/X'), ('referral', 'Referral'), ('direct', 'Direct / Manual'), ('newsletter', 'Newsletter'), ('other', 'Other')], default='other', max_length=30)),
                ('source_url', models.URLField(blank=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('contact_count', models.IntegerField(default=0)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Original scraped/imported payload')),
            ],
            options={
                'verbose_name': 'Lead Profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_email', models.EmailField(max_length=254)),
                ('seller_url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('ai_saas', 'AI / SaaS Tool'), ('dev_service', 'Dev / Implementation Service'), ('fintech', 'Fintech / Compliance'), ('healthtech', 'Healthtech / Privacy'), ('marketing', 'Marketing / Growth'), ('logistics', 'Logistics / Operations'), ('other', 'Other')], default='ai_saas', max_length=30)),
                ('description', models.TextField()),
                ('keywords', models.JSONField(default=list, help_text='List of matching keywords')),
                ('price_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pricing_model', models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly'), ('annual', 'Annual'), ('revenue_share', 'Rev Share')], default='monthly', max_length=20)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=20.0, help_text='% commission we take on each deal', max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=20)),
                ('source', models.CharField(blank=True, help_text='product_hunt, indiehackers, direct, email', max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Offer Listing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('intro', 'Intro Made'), ('negotiating', 'Negotiating'), ('contracted', 'Contracted'), ('active', 'Active / In Progress'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='intro', max_length=20)),
                ('deal_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value of the deal (seller-buyer contract)', max_digits=12)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('commission_due', models.DecimalField(decimal_places=2, default=0, help_text='Our cut = deal_value * commission_pct / 100', max_digits=12)),
                ('agreement_url', models.URLField(blank=True, help_text='Link to signed finder agreement')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('match', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='broker_ops.brokermatch')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='broker_ops.leadprofile')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='broker_ops.offerlisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('earned', 'Earned'), ('paid', 'Paid Out'), ('adjusted', 'Adjusted'), ('reversed', 'Reversed'), ('pending', 'Pending')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('stripe_payout_id', models.CharField(blank=True, max_length=200)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, help_text='External reference / invoice #', max_length=200)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='broker_ops.deal')),
            ],
            options={
                'verbose_name': 'Commission Record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='brokermatch',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='broker_ops.leadprofile'),
        ),
        migrations.AddField(
            model_name='brokermatch',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='broker_ops.offerlisting'),
        ),
        migrations.AlterUniqueTogether(
            name='brokermatch',
            unique_together={('offer', 'lead')},
        ),
    ]
