# Generated by Django 6.0.2 on 2026-03-12 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(choices=[('buyer_intro', 'Buyer Intro'), ('seller_intro', 'Seller Intro'), ('followup_1', 'Follow-up 1'), ('followup_2', 'Follow-up 2'), ('breakup', 'Breakup / Final')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('opened', 'Opened'), ('replied', 'Replied'), ('bounced', 'Bounced'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('scheduled_at', models.DateTimeField(help_text='When this email should be sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_steps', to='broker_ops.brokermatch')),
            ],
            options={
                'verbose_name': 'Outreach Sequence Step',
                'ordering': ['scheduled_at'],
                'unique_together': {('match', 'step')},
            },
        ),
    ]
