# Generated by Django 6.0.2 on 2026-03-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_ops', '0002_outreachsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokermatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='brokermatch',
            name='match_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='0-100, AI-generated'),
        ),
        migrations.AlterField(
            model_name='brokermatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Outreach Sent'), ('declined', 'Declined'), ('converted', 'Converted to Deal'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadprofile',
            name='lead_source',
            field=models.CharField(choices=[('inbound_email', 'Inbound Email'), ('product_hunt', 'Product Hunt'), ('linkedin', 'LinkedIn'), ('twitter_x', 'Twitter/X'), ('referral', 'Referral'), ('direct', 'Direct / Manual'), ('newsletter', 'Newsletter'), ('reddit', 'Reddit'), ('hacker_news', 'Hacker News'), ('github', 'GitHub'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='offerlisting',
            name='category',
            field=models.CharField(choices=[('ai_saas', 'AI / SaaS Tool'), ('dev_service', 'Dev / Implementation Service'), ('fintech', 'Fintech / Compliance'), ('healthtech', 'Healthtech / Privacy'), ('marketing', 'Marketing / Growth'), ('logistics', 'Logistics / Operations'), ('other', 'Other')], db_index=True, default='ai_saas', max_length=30),
        ),
        migrations.AlterField(
            model_name='offerlisting',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('draft', 'Draft')], db_index=True, default='active', max_length=20),
        ),
    ]
