# Generated by Django 6.0.2 on 2026-03-20 01:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_ops', '0003_alter_brokermatch_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorBuyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('buyer_type', models.CharField(choices=[('fix_flip', 'Fix & Flip'), ('buy_hold', 'Buy & Hold / Rental'), ('developer', 'Developer / New Construction'), ('landlord', 'Landlord Portfolio'), ('fund', 'Investment Fund / REIT'), ('owner_occ', 'Owner Occupant'), ('other', 'Other')], default='fix_flip', max_length=20)),
                ('markets', models.JSONField(default=list, help_text='List of city/state or zip codes they buy in')),
                ('property_types', models.JSONField(default=list, help_text='sfr, multi, land, etc.')),
                ('budget_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('can_close_days', models.IntegerField(default=14, help_text='How fast they can close (days)')),
                ('cash_buyer', models.BooleanField(default=True)),
                ('proof_of_funds', models.BooleanField(default=False, help_text='Has provided POF')),
                ('deals_closed', models.IntegerField(default=0, help_text='Total deals closed with us')),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('avg_response_hrs', models.FloatField(default=0, help_text='Avg hours to respond to a deal')),
                ('is_active', models.BooleanField(default=True)),
                ('last_deal_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='reia, facebook, direct, referral', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Investor Buyer',
                'ordering': ['-deals_closed', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='offerlisting',
            name='category',
            field=models.CharField(choices=[('ai_saas', 'AI / SaaS Tool'), ('dev_service', 'Dev / Implementation Service'), ('fintech', 'Fintech / Compliance'), ('healthtech', 'Healthtech / Privacy'), ('marketing', 'Marketing / Growth'), ('logistics', 'Logistics / Operations'), ('real_estate', 'Real Estate / Property'), ('website', 'Website / Domain'), ('other', 'Other')], db_index=True, default='ai_saas', max_length=30),
        ),
        migrations.CreateModel(
            name='PropertyLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('property_type', models.CharField(choices=[('sfr', 'Single Family'), ('multi', 'Multi-Family (2-4)'), ('apartment', 'Apartment (5+)'), ('condo', 'Condo / Townhouse'), ('land', 'Vacant Land'), ('commercial', 'Commercial'), ('mobile', 'Mobile Home')], default='sfr', max_length=20)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('sqft', models.IntegerField(default=0)),
                ('lot_sqft', models.IntegerField(default=0)),
                ('year_built', models.IntegerField(default=0)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('owner_phone', models.CharField(blank=True, max_length=20)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('owner_mailing', models.CharField(blank=True, help_text='If different from property address', max_length=300)),
                ('is_absentee', models.BooleanField(default=False)),
                ('asking_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_arv', models.DecimalField(decimal_places=2, default=0, help_text='After Repair Value', max_digits=12)),
                ('estimated_repair', models.DecimalField(decimal_places=2, default=0, help_text='Estimated repair costs', max_digits=12)),
                ('max_offer', models.DecimalField(decimal_places=2, default=0, help_text='70% ARV - repairs - assignment fee', max_digits=12)),
                ('assignment_fee', models.DecimalField(decimal_places=2, default=10000, help_text='Our wholesale fee (typically $5k-$25k)', max_digits=12)),
                ('lead_type', models.CharField(choices=[('pre_foreclosure', 'Pre-Foreclosure'), ('tax_lien', 'Tax Lien / Delinquent'), ('probate', 'Probate / Estate'), ('absentee', 'Absentee Owner'), ('divorce', 'Divorce'), ('code_violation', 'Code Violation'), ('high_equity', 'High Equity / Tired Landlord'), ('vacant', 'Vacant Property'), ('fsbo', 'For Sale By Owner'), ('expired_listing', 'Expired MLS Listing'), ('zillow', 'Zillow / Public Listing'), ('other', 'Other')], default='other', max_length=20)),
                ('motivation_score', models.IntegerField(default=0, help_text='0-100, how motivated is the seller')),
                ('equity_pct', models.DecimalField(decimal_places=2, default=0, help_text='Estimated equity percentage', max_digits=5)),
                ('days_on_market', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('negotiating', 'Negotiating'), ('under_contract', 'Under Contract'), ('assigned', 'Assigned to Buyer'), ('closed', 'Closed'), ('dead', 'Dead / No Deal')], db_index=True, default='new', max_length=20)),
                ('source', models.CharField(blank=True, help_text='zillow, propstream, tax_records, driving_for_dollars', max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('zillow_url', models.URLField(blank=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('contact_count', models.IntegerField(default=0)),
                ('contact_method', models.CharField(blank=True, help_text='sms, cold_call, direct_mail, email', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Original scraped data')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='broker_ops.deal')),
            ],
            options={
                'verbose_name': 'Property Lead',
                'ordering': ['-motivation_score', '-created_at'],
            },
        ),
    ]
