# Generated by Django 6.0.2 on 2026-03-30 02:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_ops', '0004_investorbuyer_alter_offerlisting_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlisting',
            name='seller_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(help_text='Seller / property owner name', max_length=200)),
                ('property_address', models.CharField(max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_contract', 'Under Contract'), ('closing', 'Closing'), ('closed', 'Closed'), ('dead', 'Dead')], db_index=True, default='active', max_length=20)),
                ('contract_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('assignment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('buyer_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_arv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('title_company', models.CharField(blank=True, max_length=200)),
                ('title_contact', models.CharField(blank=True, max_length=200)),
                ('title_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_files', to='broker_ops.investorbuyer')),
                ('deal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_file', to='broker_ops.deal')),
                ('property_lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_file', to='broker_ops.propertylead')),
            ],
            options={
                'verbose_name': 'Client File',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('seller_outreach', 'Seller Outreach Email'), ('deal_sheet', 'Deal Sheet / Investor Presentation'), ('assignment_contract', 'Assignment Contract'), ('buyer_pitch', 'Buyer Pitch Email'), ('title_engagement', 'Title Company Engagement'), ('signed_contract', 'Signed Contract'), ('closing_statement', 'Closing Statement'), ('payment_receipt', 'Payment Receipt'), ('addendum', 'Addendum / Amendment'), ('note', 'Internal Note'), ('other', 'Other')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('signed', 'Signed'), ('final', 'Final'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('html_content', models.TextField(blank=True, help_text='Branded HTML document content')),
                ('plain_text', models.TextField(blank=True, help_text='Plain text fallback')),
                ('to_email', models.EmailField(blank=True, max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.CharField(blank=True, help_text='Agent name: piper, rex, ace, hammer', max_length=50)),
                ('slack_message_id', models.CharField(blank=True, max_length=100)),
                ('supabase_id', models.CharField(blank=True, help_text='Synced Supabase record ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='broker_ops.clientfile')),
            ],
            options={
                'verbose_name': 'Client Document',
                'ordering': ['created_at'],
            },
        ),
    ]
