# Generated by Django 6.0.2 on 2026-02-26 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(default='#c9a84c', max_length=7)),
                ('icon_class', models.CharField(default='fa-robot', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('query', models.TextField()),
                ('mode', models.CharField(choices=[('full', 'Full Dispatch'), ('lite', 'Lite (Perplexity Only)'), ('all', 'All Agents Forced')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('routed_to', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('war_room_dir', models.CharField(blank=True, max_length=500)),
                ('combined_summary', models.TextField(blank=True)),
                ('intel_summary', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('source', models.CharField(choices=[('cli', 'CLI (hive command)'), ('dashboard', 'Dashboard'), ('api', 'API'), ('bot', 'XLM Bot')], default='cli', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hive.hivesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('done', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('skipped', 'Skipped')], max_length=20)),
                ('response_text', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('employees_consulted', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hive.agent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hive.hivesession')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('session', 'agent')},
            },
        ),
    ]
