# Generated by Django 6.0.2 on 2026-03-10 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('spend_threshold_cents', models.IntegerField(help_text='Lifetime spend in cents to trigger (e.g. 5000 = $50)')),
                ('comp_type', models.CharField(choices=[('service_voucher', 'Everlight Service Voucher'), ('free_month', 'Free Month of Subscription'), ('merch', 'Everlight Merch'), ('chips_bonus', 'Bonus Blackjack Chips'), ('gems_bonus', 'Bonus Gems'), ('vip_trial', 'Free VIP Trial'), ('cash_back', 'Cash Back Credit'), ('custom', 'Custom Comp')], max_length=30)),
                ('product_filter', models.CharField(choices=[('all', 'All Products'), ('alley_kingz_vip', 'Alley Kingz VIP'), ('onyx_pro', 'Onyx POS Pro'), ('hivemind_starter', 'Hive Mind Starter'), ('hivemind_pro', 'Hive Mind Pro'), ('hivemind_enterprise', 'Hive Mind Enterprise')], default='all', max_length=50)),
                ('comp_value', models.CharField(blank=True, help_text="Display value e.g. '$20 service credit', '500 chips'", max_length=200)),
                ('points_cost', models.IntegerField(default=0, help_text='Points player must spend to redeem (0 = auto-triggered at threshold)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_repeating', models.BooleanField(default=False, help_text='Triggers again at each multiple of threshold (e.g. every $50)')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['spend_threshold_cents', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DailyLoginReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_day', models.IntegerField(unique=True)),
                ('points_reward', models.IntegerField(default=15)),
                ('is_milestone', models.BooleanField(default=False, help_text='Show special UI treatment')),
                ('chips_bonus', models.IntegerField(default=0, help_text='Bonus blackjack chips')),
                ('gems_bonus', models.IntegerField(default=0, help_text='Bonus gems')),
                ('label', models.CharField(blank=True, help_text='Display text', max_length=100)),
            ],
            options={
                'ordering': ['streak_day'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.IntegerField(default=0, help_text='Spendable points balance')),
                ('points_lifetime', models.IntegerField(default=0, help_text='All-time earned (used for tier calculation)')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('legend', 'Legend')], default='bronze', max_length=20)),
                ('total_spent_cents', models.IntegerField(default=0, help_text='Lifetime spend in cents')),
                ('last_login_reward_date', models.DateField(blank=True, null=True)),
                ('login_streak', models.IntegerField(default=0)),
                ('referral_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('referral_count', models.IntegerField(default=0, help_text='Successful referrals made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='payments.customer')),
            ],
            options={
                'ordering': ['-points_lifetime'],
            },
        ),
        migrations.CreateModel(
            name='CompReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Fulfillment'), ('notified', 'Customer Notified'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('comp_type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Fulfillment notes')),
                ('threshold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rewards.compthreshold')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comps', to='rewards.loyaltyaccount')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn_purchase', 'Earned: Purchase'), ('earn_referral', 'Earned: Referral Bonus'), ('earn_login', 'Earned: Daily Login'), ('earn_streak', 'Earned: Login Streak Milestone'), ('earn_signup', 'Earned: Signup Bonus'), ('earn_promo', 'Earned: Promo / Admin'), ('spend_comp', 'Spent: Comp Redemption'), ('spend_reward', 'Spent: Reward Redemption'), ('expire', 'Expired'), ('adjust', 'Admin Adjustment')], max_length=30)),
                ('points', models.IntegerField(help_text='Positive = earn, negative = spend')),
                ('balance_after', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('reference_id', models.CharField(blank=True, help_text='Payment ID, session ID, etc.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rewards.loyaltyaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_email', models.EmailField(max_length=254)),
                ('referral_code_used', models.CharField(max_length=12)),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('converted', models.BooleanField(default=False, help_text='Made their first purchase?')),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('referrer_points_awarded', models.IntegerField(default=0)),
                ('referee_points_awarded', models.IntegerField(default=0)),
                ('referee_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by', to='payments.customer')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='rewards.loyaltyaccount')),
            ],
            options={
                'ordering': ['-signed_up_at'],
                'unique_together': {('referrer', 'referee_email')},
            },
        ),
    ]
