# Generated by Django 6.0.2 on 2026-03-15 01:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('source', models.CharField(db_index=True, max_length=64)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('warning', 'Warning'), ('failed', 'Failed'), ('info', 'Info')], db_index=True, default='info', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('revenue_impact_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('requires_approval', models.BooleanField(db_index=True, default=False)),
                ('owner_agent', models.CharField(blank=True, db_index=True, max_length=100)),
                ('summary', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('owner_agent', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('building', 'Building'), ('pilot', 'Pilot'), ('active', 'Active'), ('watch', 'Watch'), ('paused', 'Paused')], db_index=True, default='building', max_length=20)),
                ('monthly_target_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mrr_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_today_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_30d_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_pipeline_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_key', models.CharField(blank=True, db_index=True, max_length=160)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='warning', max_length=20)),
                ('state', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('source', models.CharField(db_index=True, max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('requires_approval', models.BooleanField(db_index=True, default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='business_os.businessevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
