# Generated by Django 6.0.2 on 2026-03-05 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('api_credential', 'API / Credential Setup'), ('social_media', 'Social Media Account'), ('email_account', 'Email Account'), ('domain', 'Domain / Hosting'), ('payment', 'Payment / Billing'), ('ai_agent', 'AI Agent Config'), ('general', 'General Task')], default='general', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-solid fa-clipboard-list', help_text='Font Awesome icon class', max_length=50)),
                ('schema', models.JSONField(help_text='Form field definitions (JSON array)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, help_text='AI-provided context for the task')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Normal'), (4, 'Low'), (5, 'Optional')], default=3)),
                ('source_agent', models.CharField(blank=True, help_text='Which AI agent created this', max_length=100)),
                ('target_agent', models.CharField(blank=True, help_text='Which agent should receive the data', max_length=100)),
                ('batch_id', models.CharField(blank=True, help_text='Groups related tasks together', max_length=100)),
                ('data_encrypted', models.TextField(blank=True, help_text='Encrypted submitted form data')),
                ('notes', models.TextField(blank=True, help_text='Human notes during completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retrieved_by_agent', models.BooleanField(default=False)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='taskboard.tasktemplate')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
