#!/usr/bin/env python3
"""build_command_center.py -- generate ev_data.js for the Everlight Command Center.

Folds real local sources into one snapshot the static pages read (served at
:2200/reports/). Runs on the phone via the band watchdog (Action 4), throttled.
Everything degrades gracefully -- a missing source just yields null/empty.

  python3 03_AUTOMATION_CORE/01_Scripts/build_command_center.py
"""
import json
import re
import time
import urllib.request
from pathlib import Path

ROOT = Path("/mnt/sdcard/AA_MY_DRIVE")
REPORTS = ROOT / "09_DASHBOARD" / "reports"
OUT = REPORTS / "ev_data.js"
TODO = ROOT / "_state" / "ops_todo.md"
ROSTER = ROOT / "06_DEVELOPMENT" / "everlight_os" / "hive_mind" / "roster.yaml"

# chrome files that are NOT "reports"
SKIP = {"ops.html", "kalshi.html", "watchdog.html", "ev_data.js"}

BANDS = [(2000, "Hub"), (2100, "Markets / XLM"), (2200, "Reports / Ops"), (2300, "Intel"),
         (2301, "Intel API"), (2302, "E-Sign"), (2400, "Apps"), (2500, "MMA / Health"),
         (2700, "Blinko RAG"), (2701, "MCP Bridge"), (2702, "Lucrex")]

# Static AI-tools registry (copy-paste launchers live on cc_ai.html)
AI_TOOLS = [
    {"key": "claude", "name": "Claude (Code)", "blurb": "Primary executor -- builds, edits, ships.",
     "use_when": "Anything that touches the repo, files, or multi-step work.", "prompt": "claude"},
    {"key": "codex", "name": "Codex", "blurb": "Cross-check reviewer + iOS/architecture validation.",
     "use_when": "Second opinion on code/architecture before shipping.", "prompt": "clx_delegate.py --mode review"},
    {"key": "gemini", "name": "Gemini", "blurb": "Alternate-perspective check, long-context explain.",
     "use_when": "Want a different model's read on a plan or doc.", "prompt": "gemx_delegate.py --mode explain"},
    {"key": "perplexity", "name": "Perplexity", "blurb": "Real-time research with citations.",
     "use_when": "Market-facing / current-events questions.", "prompt": "ppx_terminal.py"},
    {"key": "hive", "name": "Hive Mind", "blurb": "42+ named agents across departments, auto-dispatch.",
     "use_when": "Multi-domain decisions, audits, $100+ stakes.", "prompt": "hive"},
]


def read_text(p):
    try:
        return Path(p).read_text()
    except Exception:
        return ""


def pt(ts):
    return time.strftime("%Y-%m-%d %H:%M PT", time.localtime(ts - 8 * 3600))


def kalshi():
    try:
        return json.loads((REPORTS / "kalshi_summary.json").read_text())
    except Exception:
        return None


def todo():
    out, section = [], "General"
    for ln in read_text(TODO).splitlines():
        s = ln.strip()
        if not s or s.startswith("# "):
            continue
        if s.startswith("## "):
            section = s[3:].strip(); continue
        m = re.match(r"- \[([ xX])\]\s*(.+)", s)
        if m:
            out.append({"section": section, "text": m.group(2).strip(), "done": m.group(1).lower() == "x"})
    return out


def reports():
    out = []
    for f in sorted(REPORTS.glob("*.html")) + sorted(REPORTS.glob("*.md")):
        if f.name in SKIP or f.name.startswith("ev_") or f.name.startswith("cc_"):
            continue
        try:
            mt = f.stat().st_mtime
        except Exception:
            mt = 0
        out.append({"name": f.stem.replace("_", " "), "file": f.name,
                    "kind": f.suffix.lstrip("."), "mtime_pt": pt(mt), "mtime": int(mt)})
    out.sort(key=lambda x: -x["mtime"])
    return out


def hive():
    txt = read_text(ROSTER)
    if not txt:
        return {"agents": None, "tools": 28, "sample": []}
    names = re.findall(r"^\s*-?\s*name:\s*['\"]?([^'\"\n]+)", txt, re.M)
    roles = re.findall(r"^\s*role:\s*['\"]?([^'\"\n]+)", txt, re.M)
    sample = [{"name": n.strip(), "role": (roles[i].strip() if i < len(roles) else "")} for i, n in enumerate(names[:12])]
    return {"agents": len(names) or None, "tools": 28, "sample": sample}


def services():
    out = []
    for port, name in BANDS:
        up = False
        try:
            urllib.request.urlopen("http://127.0.0.1:%d/" % port, timeout=2)
            up = True
        except urllib.error.HTTPError:
            up = True            # answered (even 404) = the server is up
        except Exception:
            up = False
        out.append({"port": port, "name": name, "up": up})
    return out


def main():
    data = {
        "generated_ts": int(time.time()),
        "generated_pt": pt(time.time()),
        "kalshi": kalshi(),
        "todo": todo(),
        "reports": reports(),
        "hive": hive(),
        "services": services(),
        "ai_tools": AI_TOOLS,
    }
    REPORTS.mkdir(parents=True, exist_ok=True)
    OUT.write_text("/* generated by build_command_center.py -- do not edit */\nwindow.EV_DATA = "
                   + json.dumps(data, ensure_ascii=False) + ";\n")
    k = data["kalshi"] or {}
    print("ev_data.js written: %d todo, %d reports, %d services up, kalshi=%s" % (
        len(data["todo"]), len(data["reports"]),
        sum(1 for s in data["services"] if s["up"]),
        ("$%.2f" % k["balance"]) if k.get("balance") is not None else "n/a"))


if __name__ == "__main__":
    main()
