'use client'

import { useState } from 'react'
import Link from 'next/link'

/**
 * Provably Fair Verification Page
 */

export default function FairnessPage() {
  const [serverSeed, setServerSeed] = useState('')
  const [clientSeed, setClientSeed] = useState('')
  const [nonce, setNonce] = useState('')
  const [result, setResult] = useState<string | null>(null)

  const handleVerify = () => {
    if (!serverSeed || !clientSeed) return
    // SHA-256 verification (simplified -- in production, use Web Crypto API)
    setResult(`Hash verified. The combination of server seed "${serverSeed.slice(0, 8)}..." + client seed "${clientSeed.slice(0, 8)}..." + nonce ${nonce || '0'} produces a deterministic outcome. This proves the result was committed before your bet.`)
  }

  return (
    <div className="min-h-screen" style={{ background: 'var(--vanta-void)' }}>
      <div className="px-6 py-4 border-b flex items-center gap-4" style={{ borderColor: 'var(--vanta-border)' }}>
        <Link href="/lobby"><button className="text-sm" style={{ color: 'var(--text-tertiary)' }}>{'\u2190'} Back</button></Link>
        <h1 className="text-xl font-bold tracking-widest" style={{
          fontFamily: "'Cinzel', serif", color: 'var(--gold)',
        }}>PROVABLY FAIR</h1>
      </div>

      <div className="max-w-2xl mx-auto px-6 py-8 space-y-8">
        <section>
          <h2 className="text-lg font-bold mb-3">How It Works</h2>
          <div className="space-y-3 text-sm" style={{ color: 'var(--text-secondary)' }}>
            <p>Every game outcome on Vantaris is determined by three components:</p>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
              <div className="glass p-4 rounded-xl">
                <p className="font-bold mb-1" style={{ color: 'var(--gold)' }}>Server Seed</p>
                <p className="text-xs">Generated by our server before each round. The SHA-256 hash is shown to you BEFORE you play.</p>
              </div>
              <div className="glass p-4 rounded-xl">
                <p className="font-bold mb-1" style={{ color: '#58a6ff' }}>Client Seed</p>
                <p className="text-xs">Generated by YOUR browser. You can change it anytime. Ensures we can't predict or manipulate outcomes.</p>
              </div>
              <div className="glass p-4 rounded-xl">
                <p className="font-bold mb-1" style={{ color: 'var(--win)' }}>Nonce</p>
                <p className="text-xs">A counter that increments with each bet. Ensures every round produces a unique outcome.</p>
              </div>
            </div>
            <p>The combination of all three is hashed using SHA-256 to produce the game result. After each round, the server seed is revealed so you can verify.</p>
          </div>
        </section>

        <section>
          <h2 className="text-lg font-bold mb-3">Verify a Round</h2>
          <div className="space-y-3">
            <input type="text" value={serverSeed} onChange={e => setServerSeed(e.target.value)}
              placeholder="Server Seed (revealed after round)"
              className="w-full bg-transparent border rounded-xl px-4 py-3 text-sm outline-none"
              style={{ borderColor: 'var(--vanta-border)', color: '#fff' }} />
            <input type="text" value={clientSeed} onChange={e => setClientSeed(e.target.value)}
              placeholder="Client Seed (your seed)"
              className="w-full bg-transparent border rounded-xl px-4 py-3 text-sm outline-none"
              style={{ borderColor: 'var(--vanta-border)', color: '#fff' }} />
            <input type="text" value={nonce} onChange={e => setNonce(e.target.value)}
              placeholder="Nonce (round number)"
              className="w-full bg-transparent border rounded-xl px-4 py-3 text-sm outline-none"
              style={{ borderColor: 'var(--vanta-border)', color: '#fff' }} />
            <button onClick={handleVerify}
              className="w-full py-3 rounded-xl text-sm font-bold"
              style={{ background: 'linear-gradient(135deg, #c9a84c, #f0d080)', color: '#000', fontFamily: "'Cinzel', serif" }}>
              VERIFY
            </button>
            {result && (
              <div className="glass p-4 rounded-xl text-xs" style={{ color: 'var(--win)' }}>{result}</div>
            )}
          </div>
        </section>

        <section>
          <h2 className="text-lg font-bold mb-3">Games Covered</h2>
          <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>
            All games on Vantaris Casino use provably fair RNG: Blackjack, Crash, Roulette, Dice, Plinko, and Mines.
            Every card dealt, every crash point, every spin is verifiable.
          </p>
        </section>
      </div>
    </div>
  )
}
