"""Everlight styled HTML report template for the 3-format reporting pipeline."""
from __future__ import annotations

from datetime import datetime, timezone


def _now_pt() -> str:
    try:
        from zoneinfo import ZoneInfo
        return datetime.now(ZoneInfo("America/Los_Angeles")).strftime("%B %d, %Y %I:%M %p PT")
    except Exception:
        return datetime.now(timezone.utc).strftime("%B %d, %Y %H:%M UTC")


def _now_short() -> str:
    try:
        from zoneinfo import ZoneInfo
        return datetime.now(ZoneInfo("America/Los_Angeles")).strftime("%Y%m%d_%H%M")
    except Exception:
        return datetime.now(timezone.utc).strftime("%Y%m%d_%H%M")


EVERLIGHT_CSS = """
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Playfair+Display:wght@400;600;700&display=swap');
* { margin: 0; padding: 0; box-sizing: border-box; }
body { background: #0A0A0A; color: #E8E8E8; font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif; line-height: 1.7; min-height: 100vh; }
.header { background: linear-gradient(135deg, #0A0A0A 0%, #1A1A1A 100%); border-bottom: 2px solid #D4AF37; padding: 40px 0; text-align: center; }
.header-inner { max-width: 800px; margin: 0 auto; padding: 0 24px; }
.logo { font-family: 'Playfair Display', serif; font-size: 14px; letter-spacing: 4px; text-transform: uppercase; color: #D4AF37; margin-bottom: 16px; }
.header h1 { font-family: 'Playfair Display', serif; font-size: 28px; font-weight: 600; color: #E8E8E8; margin-bottom: 8px; }
.header .meta { font-size: 13px; color: #999999; }
.header .meta span { color: #D4AF37; }
.content { max-width: 800px; margin: 0 auto; padding: 40px 24px; }
.content h2 { font-family: 'Playfair Display', serif; font-size: 22px; color: #D4AF37; margin: 32px 0 16px 0; padding-bottom: 8px; border-bottom: 1px solid #1A1A1A; }
.content h3 { font-size: 16px; font-weight: 600; color: #E8E8E8; margin: 24px 0 12px 0; }
.content p { margin-bottom: 16px; font-size: 15px; }
.content ul { margin: 0 0 16px 24px; }
.content li { margin-bottom: 8px; font-size: 15px; }
.content strong { color: #D4AF37; font-weight: 600; }
table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 14px; }
th { background: #1A1A1A; color: #D4AF37; text-align: left; padding: 12px 16px; font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; }
td { padding: 10px 16px; border-bottom: 1px solid #1a1a1a; }
tr:hover td { background: #1A1A1A; }
.footer { text-align: center; padding: 40px 24px; color: #999999; font-size: 12px; border-top: 1px solid #1a1a1a; }
.footer .brand { color: #D4AF37; font-family: 'Playfair Display', serif; font-size: 14px; letter-spacing: 2px; }
.sig { margin-top: 40px; padding-top: 20px; border-top: 1px solid #222; }
.sig .name { color: #D4AF37; font-weight: 600; font-size: 15px; }
.sig .role, .sig .contact { color: #999; font-size: 13px; }
"""


def render_report(
    *,
    title: str,
    content_html: str,
    agent_name: str = "Everlight Ventures",
    agent_title: str = "Automated Intelligence",
    agent_email: str = "hello@everlightventures.io",
    confidential: bool = False,
) -> str:
    ts = _now_pt()
    conf_badge = ' | <span>CONFIDENTIAL</span>' if confidential else ''
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} | Everlight Ventures</title>
<style>{EVERLIGHT_CSS}</style>
</head>
<body>
<div class="header">
  <div class="header-inner">
    <div class="logo">Everlight Ventures</div>
    <h1>{title}</h1>
    <div class="meta">Prepared by <span>{agent_name}</span> | {ts}{conf_badge}</div>
  </div>
</div>
<div class="content">
{content_html}
<div class="sig">
  <div class="name">{agent_name}</div>
  <div class="role">{agent_title}</div>
  <div class="contact">{agent_email} | everlightventures.io</div>
</div>
</div>
<div class="footer">
  <div class="brand">Everlight Ventures</div>
  <p style="margin-top: 8px;">Generated by the Everlight Hive Mind | Sacramento, CA</p>
  <p style="margin-top: 4px;">everlightventures.io</p>
</div>
</body>
</html>"""


def safe_filename(title: str) -> str:
    clean = title.lower().replace(" ", "_").replace("/", "_").replace("--", "_")
    clean = "".join(c for c in clean if c.isalnum() or c == "_")
    return f"{clean}_{_now_short()}.html"
