# Generated by Django 6.0.2 on 2026-03-05 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('product', models.CharField(choices=[('onyx', 'Onyx POS'), ('hivemind', 'Hive Mind SaaS')], max_length=20)),
                ('source', models.CharField(blank=True, help_text='e.g. tiktok, twitter, direct', max_length=100)),
                ('funnel_stage', models.CharField(choices=[('captured', 'Captured'), ('welcome_sent', 'Welcome Sent'), ('nurturing', 'Nurturing'), ('trial_started', 'Trial Started'), ('converted', 'Converted'), ('churned', 'Churned')], default='captured', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emails_sent', models.IntegerField(default=0)),
                ('last_email_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='e.g. page_view, signup, email_sent, email_opened, trial_start', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='funnel.lead')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
