# Generated by Django 6.0.2 on 2026-03-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnel', '0002_alter_lead_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='product',
            field=models.CharField(choices=[('onyx', 'Onyx POS'), ('hivemind', 'Hive Mind SaaS'), ('dashboard', 'Trading Watchtower'), ('ai_consulting', 'AI Consulting')], max_length=20),
        ),
    ]
