"""
Device Management API
Multi-device access control with tier-based limits
"""
from flask import Blueprint, request, jsonify, g
from flask_jwt_extended import jwt_required, get_jwt_identity
from models import DeviceSession, Tenant, User
from datetime import datetime, timedelta
import hashlib

devices_bp = Blueprint("devices", __name__)


def generate_device_fingerprint(user_agent, ip_address, device_id):
    """Generate unique fingerprint for device"""
    data = f"{user_agent}:{ip_address}:{device_id}"
    return hashlib.sha256(data.encode()).hexdigest()


@devices_bp.route("/register", methods=["POST"])
@jwt_required()
def register_device():
    """
    Register a new device session

    Request body:
    - device_id: Unique device identifier (UUID generated by client)
    - device_name: User-friendly name (e.g., "John's iPhone")
    - device_type: mobile, tablet, desktop, pos_terminal
    - platform: ios, android, web, windows, macos
    """
    try:
        tenant_id = g.tenant_id
        user_id = get_jwt_identity()
        data = request.json

        # Get tenant to check device limits
        tenant = g.db.query(Tenant).filter_by(id=tenant_id).first()
        if not tenant:
            return jsonify({"error": "Tenant not found"}), 404

        # Get device limit for this tier
        device_limit = tenant.get_device_limit()

        # Count active devices for this tenant
        active_devices = g.db.query(DeviceSession).filter_by(
            tenant_id=tenant_id,
            is_active=True
        ).count()

        # Check if limit reached (0 = unlimited)
        if device_limit > 0 and active_devices >= device_limit:
            return jsonify({
                "error": "Device limit reached",
                "message": f"Your {tenant.plan_tier} plan allows {device_limit} devices. Upgrade to add more devices.",
                "current_devices": active_devices,
                "device_limit": device_limit,
                "upgrade_recommended": "growth" if tenant.plan_tier == "core" else "prime"
            }), 403

        # Check if this device is already registered
        device_id = data.get("device_id")
        existing = g.db.query(DeviceSession).filter_by(
            tenant_id=tenant_id,
            device_id=device_id
        ).first()

        # Get request metadata
        user_agent = request.headers.get("User-Agent", "Unknown")
        ip_address = request.remote_addr
        fingerprint = generate_device_fingerprint(user_agent, ip_address, device_id)

        if existing:
            # Update existing device
            existing.device_name = data.get("device_name", existing.device_name)
            existing.device_type = data.get("device_type", existing.device_type)
            existing.platform = data.get("platform", existing.platform)
            existing.user_agent = user_agent
            existing.ip_address = ip_address
            existing.fingerprint = fingerprint
            existing.is_active = True
            existing.last_active_at = datetime.utcnow()
            existing.expires_at = datetime.utcnow() + timedelta(days=30)

            g.db.commit()

            return jsonify({
                "message": "Device session updated",
                "device": {
                    "id": existing.id,
                    "device_id": existing.device_id,
                    "device_name": existing.device_name,
                    "is_active": existing.is_active
                }
            }), 200

        # Create new device session
        device = DeviceSession(
            tenant_id=tenant_id,
            user_id=user_id,
            device_id=device_id,
            device_name=data.get("device_name", "Unknown Device"),
            device_type=data.get("device_type", "unknown"),
            platform=data.get("platform", "unknown"),
            user_agent=user_agent,
            ip_address=ip_address,
            fingerprint=fingerprint,
            is_active=True,
            last_active_at=datetime.utcnow(),
            expires_at=datetime.utcnow() + timedelta(days=30)
        )

        g.db.add(device)
        g.db.commit()

        return jsonify({
            "message": "Device registered successfully",
            "device": {
                "id": device.id,
                "device_id": device.device_id,
                "device_name": device.device_name,
                "device_type": device.device_type,
                "platform": device.platform
            },
            "tier_info": {
                "plan_tier": tenant.plan_tier,
                "device_limit": device_limit if device_limit > 0 else "unlimited",
                "devices_used": active_devices + 1,
                "devices_remaining": (device_limit - active_devices - 1) if device_limit > 0 else "unlimited"
            }
        }), 201

    except Exception as e:
        g.db.rollback()
        return jsonify({"error": str(e)}), 500


@devices_bp.route("", methods=["GET"])
@jwt_required()
def list_devices():
    """List all devices for tenant"""
    try:
        tenant_id = g.tenant_id

        devices = g.db.query(DeviceSession).filter_by(
            tenant_id=tenant_id
        ).order_by(DeviceSession.last_active_at.desc()).all()

        tenant = g.db.query(Tenant).filter_by(id=tenant_id).first()
        device_limit = tenant.get_device_limit()

        return jsonify({
            "devices": [
                {
                    "id": device.id,
                    "device_id": device.device_id,
                    "device_name": device.device_name,
                    "device_type": device.device_type,
                    "platform": device.platform,
                    "user_id": device.user_id,
                    "user_name": device.user.full_name if device.user else None,
                    "is_active": device.is_active,
                    "last_active_at": device.last_active_at.isoformat(),
                    "created_at": device.created_at.isoformat()
                }
                for device in devices
            ],
            "tier_info": {
                "plan_tier": tenant.plan_tier,
                "device_limit": device_limit if device_limit > 0 else "unlimited",
                "active_devices": len([d for d in devices if d.is_active]),
                "total_devices": len(devices)
            }
        }), 200

    except Exception as e:
        return jsonify({"error": str(e)}), 500


@devices_bp.route("/<device_id>", methods=["DELETE"])
@jwt_required()
def deactivate_device(device_id):
    """Deactivate a device"""
    try:
        tenant_id = g.tenant_id
        user_id = get_jwt_identity()

        device = g.db.query(DeviceSession).filter_by(
            id=device_id,
            tenant_id=tenant_id
        ).first()

        if not device:
            return jsonify({"error": "Device not found"}), 404

        # Check if user is owner/manager or owns this device
        user = g.db.query(User).filter_by(id=user_id).first()
        if user.role not in ["owner", "manager"] and device.user_id != user_id:
            return jsonify({"error": "Unauthorized"}), 403

        device.is_active = False
        g.db.commit()

        return jsonify({"message": "Device deactivated successfully"}), 200

    except Exception as e:
        g.db.rollback()
        return jsonify({"error": str(e)}), 500


@devices_bp.route("/heartbeat", methods=["POST"])
@jwt_required()
def device_heartbeat():
    """Update device last active timestamp"""
    try:
        tenant_id = g.tenant_id
        data = request.json
        device_id = data.get("device_id")

        device = g.db.query(DeviceSession).filter_by(
            tenant_id=tenant_id,
            device_id=device_id,
            is_active=True
        ).first()

        if device:
            device.last_active_at = datetime.utcnow()
            g.db.commit()

        return jsonify({"status": "ok"}), 200

    except Exception as e:
        return jsonify({"error": str(e)}), 500


@devices_bp.route("/limits", methods=["GET"])
@jwt_required()
def get_limits():
    """Get device and team size limits for current plan"""
    try:
        tenant_id = g.tenant_id

        tenant = g.db.query(Tenant).filter_by(id=tenant_id).first()
        if not tenant:
            return jsonify({"error": "Tenant not found"}), 404

        device_limit = tenant.get_device_limit()
        team_limit = tenant.get_team_size_limit()

        # Count current usage
        active_devices = g.db.query(DeviceSession).filter_by(
            tenant_id=tenant_id,
            is_active=True
        ).count()

        team_size = g.db.query(User).filter_by(
            tenant_id=tenant_id,
            is_active=True
        ).count()

        return jsonify({
            "plan_tier": tenant.plan_tier,
            "devices": {
                "limit": device_limit if device_limit > 0 else "unlimited",
                "used": active_devices,
                "remaining": (device_limit - active_devices) if device_limit > 0 else "unlimited",
                "can_add_more": device_limit == 0 or active_devices < device_limit
            },
            "team": {
                "limit": team_limit if team_limit > 0 else "unlimited",
                "used": team_size,
                "remaining": (team_limit - team_size) if team_limit > 0 else "unlimited",
                "can_add_more": team_limit == 0 or team_size < team_limit
            }
        }), 200

    except Exception as e:
        return jsonify({"error": str(e)}), 500
