# Generated by Django 6.0.2 on 2026-03-10 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('outfit', 'Outfit'), ('accessory', 'Accessory'), ('hat', 'Hat'), ('aura', 'Aura / Hologram'), ('card_back', 'Card Back'), ('table_felt', 'Table Felt'), ('chip_style', 'Chip Style'), ('title', 'Title'), ('emote', 'Emote')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.CharField(blank=True, max_length=100)),
                ('price_chips', models.IntegerField(default=0)),
                ('price_gems', models.IntegerField(default=0)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('rank_required', models.CharField(default='Bronze', max_length=20)),
                ('is_limited', models.BooleanField(default=False)),
                ('is_vip_only', models.BooleanField(default=False)),
                ('visual_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bj_cosmetic_item',
                'ordering': ['category', 'rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GemPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gems', models.IntegerField()),
                ('bonus_gems', models.IntegerField(default=0)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bj_gem_package',
                'ordering': ['price_usd'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chips', models.BigIntegerField(default=1000)),
                ('gems', models.IntegerField(default=0)),
                ('total_chips_won', models.BigIntegerField(default=0)),
                ('total_chips_lost', models.BigIntegerField(default=0)),
                ('hands_played', models.IntegerField(default=0)),
                ('hands_won', models.IntegerField(default=0)),
                ('hands_lost', models.IntegerField(default=0)),
                ('hands_push', models.IntegerField(default=0)),
                ('blackjacks', models.IntegerField(default=0)),
                ('biggest_win', models.BigIntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('rank', models.CharField(default='Bronze', max_length=20)),
                ('rank_points', models.IntegerField(default=0)),
                ('avatar_name', models.CharField(default='Player', max_length=60)),
                ('avatar_base', models.CharField(default='silhouette_1', max_length=30)),
                ('avatar_outfit', models.CharField(default='default_suit', max_length=30)),
                ('avatar_accessory', models.CharField(default='none', max_length=30)),
                ('avatar_hat', models.CharField(default='none', max_length=30)),
                ('avatar_aura', models.CharField(default='none', max_length=30)),
                ('avatar_title', models.CharField(default='Rookie', max_length=60)),
                ('avatar_color_primary', models.CharField(default='#c9a84c', max_length=7)),
                ('avatar_color_secondary', models.CharField(default='#1a1a2e', max_length=7)),
                ('seat_number', models.IntegerField(default=1)),
                ('oauth_provider', models.CharField(blank=True, default='', max_length=20)),
                ('oauth_uid', models.CharField(blank=True, default='', max_length=100)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('ad_refills_today', models.IntegerField(default=0)),
                ('ad_refill_date', models.DateField(blank=True, null=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('vip_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bj_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bj_player_profile',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('alltime', 'All Time')], max_length=10)),
                ('rank_position', models.IntegerField()),
                ('chips_won', models.BigIntegerField(default=0)),
                ('hands_won', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackjack.playerprofile')),
            ],
            options={
                'db_table': 'bj_leaderboard',
                'ordering': ['period', 'rank_position'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=40, unique=True)),
                ('bet_chips', models.BigIntegerField(default=0)),
                ('side_bet_chips', models.BigIntegerField(default=0)),
                ('player_hand', models.JSONField(default=list)),
                ('dealer_hand', models.JSONField(default=list)),
                ('player_value', models.IntegerField(default=0)),
                ('dealer_value', models.IntegerField(default=0)),
                ('outcome', models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss'), ('push', 'Push'), ('blackjack', 'Blackjack'), ('bust', 'Bust'), ('surrender', 'Surrender')], max_length=20)),
                ('chips_delta', models.BigIntegerField(default=0)),
                ('deck_count', models.IntegerField(default=6)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('presence_multiplier', models.FloatField(default=1.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='blackjack.playerprofile')),
            ],
            options={
                'db_table': 'bj_game_session',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='AdRewardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_date', models.DateField()),
                ('chips_awarded', models.IntegerField(default=100)),
                ('ad_unit_id', models.CharField(blank=True, max_length=100)),
                ('rewarded_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_rewards', to='blackjack.playerprofile')),
            ],
            options={
                'db_table': 'bj_ad_reward_log',
            },
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('acquisition_method', models.CharField(default='purchase', max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackjack.cosmeticitem')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='blackjack.playerprofile')),
            ],
            options={
                'db_table': 'bj_player_inventory',
                'unique_together': {('player', 'item')},
            },
        ),
    ]
