# Generated by Django 6.0.2 on 2026-03-15 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0002_playerprofile_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='action_log',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='doubled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='shoe_seed',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='shoe_state',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('player_turn', 'Player Turn'), ('dealer_turn', 'Dealer Turn'), ('settled', 'Settled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='GemPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('amount_cents', models.IntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('gems_awarded', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blackjack.gempackage')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gem_purchases', to='blackjack.playerprofile')),
            ],
            options={
                'db_table': 'bj_gem_purchase',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
