"""
Slack Integration for Client File Documents

Posts branded document notifications to #ft-hunters when new documents
are generated. Includes inline preview + link to dashboard.
"""
import json
import logging
import os

import requests

from .models import ClientDocument, ClientFile

logger = logging.getLogger(__name__)

# Slack config
SLACK_BOT_TOKEN = os.environ.get("SLACK_BOT_TOKEN", "")
SLACK_CHANNEL_FT_HUNTERS = "C08NTFHBFHD"  # #ft-hunters
SLACK_CHANNEL_BROKER = "C08NT01234"  # #broker-pipeline fallback
DASHBOARD_BASE_URL = os.environ.get("DASHBOARD_BASE_URL", "http://129.159.38.250:8504")

# Doc type emoji map
DOC_EMOJI = {
    "seller_outreach": ":envelope:",
    "deal_sheet": ":page_facing_up:",
    "assignment_contract": ":memo:",
    "buyer_pitch": ":dart:",
    "title_engagement": ":classical_building:",
    "signed_contract": ":white_check_mark:",
    "closing_statement": ":moneybag:",
    "payment_receipt": ":money_with_wings:",
    "addendum": ":pushpin:",
    "note": ":notebook:",
}


def _slack_post(channel: str, blocks: list, text: str = "") -> dict:
    """Post a message to Slack using Bot Token."""
    if not SLACK_BOT_TOKEN:
        logger.warning("SLACK_BOT_TOKEN not set, skipping Slack post")
        return {}

    resp = requests.post(
        "https://slack.com/api/chat.postMessage",
        headers={
            "Authorization": f"Bearer {SLACK_BOT_TOKEN}",
            "Content-Type": "application/json",
        },
        json={
            "channel": channel,
            "text": text,
            "blocks": blocks,
            "unfurl_links": False,
        },
        timeout=10,
    )
    data = resp.json()
    if not data.get("ok"):
        logger.warning("Slack post failed: %s", data.get("error"))
    return data


def post_document_to_slack(doc: ClientDocument, channel: str = "") -> str:
    """
    Post a new document notification to Slack.
    Returns the Slack message timestamp (ts) for threading.
    """
    cf = doc.client_file
    channel = channel or SLACK_CHANNEL_FT_HUNTERS
    emoji = DOC_EMOJI.get(doc.doc_type, ":page_facing_up:")
    dashboard_url = f"{DASHBOARD_BASE_URL}/broker/client-files/{cf.id}/"
    preview_url = f"{DASHBOARD_BASE_URL}/broker/client-files/doc/{doc.id}/preview/"

    # Money formatting
    fee = f"${float(cf.assignment_fee):,.0f}"
    price = f"${float(cf.buyer_price):,.0f}"

    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"{emoji} New Document: {doc.get_doc_type_display()}",
            },
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Property:*\n{cf.property_address}"},
                {"type": "mrkdwn", "text": f"*Status:*\n{cf.get_status_display()}"},
                {"type": "mrkdwn", "text": f"*Assignment Fee:*\n{fee}"},
                {"type": "mrkdwn", "text": f"*Buyer Price:*\n{price}"},
            ],
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*{doc.title}*\nGenerated by _{doc.generated_by}_ | Status: `{doc.status}`",
            },
        },
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "View Document"},
                    "url": preview_url,
                    "style": "primary",
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Client File"},
                    "url": dashboard_url,
                },
            ],
        },
        {"type": "divider"},
    ]

    fallback_text = f"{emoji} {doc.get_doc_type_display()} for {cf.property_address} ({fee} fee)"
    result = _slack_post(channel, blocks, text=fallback_text)

    ts = result.get("ts", "")
    if ts:
        doc.slack_message_id = ts
        doc.save(update_fields=["slack_message_id"])

    return ts


def post_client_file_summary(cf: ClientFile, channel: str = "") -> str:
    """Post a summary of the entire client file to Slack."""
    channel = channel or SLACK_CHANNEL_FT_HUNTERS
    dashboard_url = f"{DASHBOARD_BASE_URL}/broker/client-files/{cf.id}/"
    docs = cf.documents.all()
    doc_list = "\n".join(
        f"  {DOC_EMOJI.get(d.doc_type, ':page_facing_up:')} {d.get_doc_type_display()} - `{d.status}`"
        for d in docs
    )

    fee = f"${float(cf.assignment_fee):,.0f}"
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f":file_folder: Client File: {cf.property_address}",
            },
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Seller:*\n{cf.client_name}"},
                {"type": "mrkdwn", "text": f"*Status:*\n{cf.get_status_display()}"},
                {"type": "mrkdwn", "text": f"*Fee:*\n{fee}"},
                {"type": "mrkdwn", "text": f"*Documents:*\n{docs.count()}"},
            ],
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Documents:*\n{doc_list}" if doc_list else "*No documents yet*",
            },
        },
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Open Client File"},
                    "url": dashboard_url,
                    "style": "primary",
                },
            ],
        },
    ]

    result = _slack_post(channel, blocks, text=f"Client File: {cf.property_address} ({fee})")
    return result.get("ts", "")
